# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HackerTon0825' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HackerTon0825

  target 'HackerTon0825Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HackerTon0825UITests' do
    # Pods for testing
  end

end
